server:
  port: 8080

spring:
  application:
    name: EchoCampus-Backend

logging:
  level:
    com.echocampus: INFO

minio:
  endpoint: http://localhost:9000
  access-key: echo_campus
  secret-key: echo_campus
  bucket: image