server:
  port: 8080

spring:
  application:
    name: EchoCampus-Backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:echo_campus}
    username: ${DB_USERNAME:echo_campus}
    password: ${DB_PASSWORD:echo_campus}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    clean-disabled: true
    clean-on-migrate: false
    validate-on-migrate: false
    locations: classpath:db/migration
  mail:
    host: smtp.qq.com
    port: 587
    username: 3292513488@qq.com
    password: qkaxjkriydildbai
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.echocampus
  type-handlers-package: com.echocampus.shared.handler
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: none
logging:
  level:
    com.echocampus: INFO

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:echo_campus}
  secret-key: ${MINIO_SECRET_KEY:echo_campus}
  bucket: ${MINIO_BUCKET:image}

callback:
  protocol: ${CALLBACK_PROTOCOL:http}
  host: ${CALLBACK_HOST:localhost}
  port: ${CALLBACK_PORT:8080}
  base-path: /api/v1/internal/callback
  # 回调超时时间（毫秒）
  timeout: ${CALLBACK_TIMEOUT:5000}
