services:
#  backend-java:
#    build:
#      context: ./backend_java
#      dockerfile: Dockerfile
#    container_name: backend-java
#    restart: always
#    ports:
#      - "8080:8080"
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_NAME: echo_campus
#      DB_USERNAME: echo_campus
#      DB_PASSWORD: echo_campus
#      MINIO_ENDPOINT: http://minio:9000
#      MINIO_ACCESS_KEY: echo_campus
#      MINIO_SECRET_KEY: echo_campus
#      MINIO_BUCKET: image
#      SPRING_RABBITMQ_HOST: rabbitmq
#      SPRING_RABBITMQ_PORT: 5672
#      SPRING_RABBITMQ_USERNAME: echo_campus
#      SPRING_RABBITMQ_PASSWORD: echo_campus
#    depends_on:
#      postgres:
#        condition: service_healthy
#      minio:
#        condition: service_started
#      rabbitmq:
#        condition: service_started

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ACCESS_KEY: echo_campus
      MINIO_SECRET_KEY: echo_campus
    volumes:
      - /home/data:/data
      - /home/config:/root/.minio
    command: server /data --address ":9000" --console-address ":9090"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: echo_campus
      RABBITMQ_DEFAULT_PASS: echo_campus
    ports:
      - "15672:15672"   # 管理界面端口
      - "5672:5672"     # 消息通信端口
    volumes:
      - /usr/local/docker/rabbitmq:/var/lib/rabbitmq

  postgres:
    image: library/postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: echo_campus
      POSTGRES_USER: echo_campus
      POSTGRES_DB: echo_campus
      TZ: Asia/Shanghai
    ports:
      - "127.0.0.1:5433:5432"
    restart: always
    volumes:
      - /data/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U echo_campus -d echo_campus"]
      interval: 5s
      timeout: 5s
      retries: 10